services:
  - type: web
    name: my-giant-bot
    env: python
    plan: free                 # <--- تم التغيير للمجاني
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:                   # <--- هذه القائمة ضرورية جداً
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: BOT_TOKEN
        sync: false            # يعني أنك ستدخل القيمة يدوياً في الموقع
      - key: MONGO_URL
        sync: false
      - key: ADMIN_PASSWORD
        value: 123             # أو sync: false لإخفائها
